### ISSUE TITLE
Any way to close port 80?

### ISSUE THREAD

**Issue by DavidFW1960** [korylprince/hassio-caddy#1]
Is it possible to not use port 80? I would really like to not leave port 80 forwarded to my Pi on my router. I am using a different port to 443 for HTTPS and SSl and would like to do the same with port 80 but I don't think this is possible??

**Comment by DavidFW1960** [comment]
shodan is now showing my RPi on port 80 and names Caddy as the server

**Comment by korylprince** [comment]
This plugin uses host networking, which means the add-on has direct access to your network interface. What this means is that it's up to you to configure Caddy which ports to use and not use.

For example, this configuration only listens on `:1234` with HTTPS:

```
https://example.com:1234 {
    tls /ssl/fullchain.pem /ssl/privkey.pem {
        alpn http/1.1
    }
}
```

and this configuration listens to port `:4321` with just normal HTTP:

```
http://example.com:4321 {
    tls off
}
```

Of particular note, if you're trying to use Automatic HTTPS, [you've got to use ports 80 and 443](https://github.com/mholt/caddy/issues/918). This is why I manually set the certs for TLS, or explicitly turn it off.

Also, I'm not exactly sure what you mean about the having port 80 open, but pretty much any router will let you forward from and to different ports. i.e 

`Internet -> Router port 12345/TCP -> Internal port 80/TCP`
