### ISSUE TITLE
Caddy V2?

### ISSUE THREAD

**Issue by DavidFW1960** [korylprince/hassio-caddy#11]
Hi Kory,

Any plans to support the new version 2?

**Comment by korylprince** [comment]
Currently alpine hasn't updated their package to Caddy 2 yet. I might investigate updating to Caddy 2 when that happens, but there are some issues...

Before that, it's technically possible to use this add-on using the [Custom Caddy binaries](https://github.com/korylprince/hassio-caddy/tree/master/caddy#custom-caddy-binaries) feature. Caddy v2 isn't CLI compatible (i.e. the flags have changed) with Caddy v1, so you'd have to do some fiddling like: 

* Place your caddy2 binary at `/share/caddy2.bin`
* Create an executable shell script (`chmod 755`) named `/share/caddy.bin` Ex:

```
#!/bin/sh
caddy adapt --config /share/Caddyfile <any other flags...>
```

The v2 Caddyfile isn't 100% compatible with v1 Caddyfile, so you'll need to update that as well.

Flags from the add-on config wouldn't be passed (so you would have to put them in the shell script), but environment variables would be.


Now as far as updating this add-on to Caddy 2... The biggest issue would be maintaining backwards compatibility. Caddy v2 CLI is not backwards compatible, and the Caddyfile isn't either. So if I suddenly updated the add-on to Caddy 2, it would break a lot of installs.

The one possibility would be to add a new add-on configuration flag that defaults to Caddy 1, but can be manually set to Caddy 2. However, this would require me to support both Caddy 1 and 2 in the add-on, as well as have to build both, etc.  I don't currently have the time to do this, but I'm not ruling it out as a future option.

In the meantime, you can use the workaround above, or try [this new Caddy 2 add-on](https://community.home-assistant.io/t/home-assistant-add-on-caddy-2/187620) that @berichta created. I haven't looked at that add-on, so I can't comment on it's stability/quality.

Finally, thanks for all the support you've provided on the home assistant forums thread for this add-on. You've been very helpful.

**Comment by DavidFW1960** [comment]
Thanks for the comprehensive response.
Seems to me that caddy v1 is not going to be supported much longer. Time will tell. Maybe a new caddy2 addon instead of maintaining compatibility?
Helping on the forums is my only means of paying you back for this great addon. I will check out the @berichta one you linked as well.

**Comment by korylprince** [comment]
I have made the decision to archive this repository. Please see the README for more information.
