### ISSUE TITLE
Feature Request: Plugins

### ISSUE THREAD

**Issue by Imperial-Guard** [korylprince/hassio-caddy#3]
I'd like to add http.login and http.jwt to my Caddy install. 

Is it possible to add a feature to select plugins in a config?

**Comment by Imperial-Guard** [comment]
Any news on this request?

**Comment by korylprince** [comment]
I'm sorry it took so long to get to this.

I've "implemented" plugins with version 1.4. Please update and read the new section "Updates/Plugins" section of the README to use a custom version of Caddy (with whatever plugins you want.)

Let me know here if you have any issues.
