### ISSUE TITLE
after updating to 1.4 , error ,  no connection to external url

### ISSUE THREAD

**Issue by gnkarn** [korylprince/hassio-caddy#5]
receive this error , and cant connect to my site using the external url

failed to get certificate: acme: Error 400 - urn:ietf:params:acme:error:connection - Fetching http: my sitexxxxx  challenge/p_AmcnNjJP6Et5vMhkHc-hSezn8U30jmn3dkV4tZUcY: Timeout during connect (likely firewall problem)
Activating privacy features...

**Comment by korylprince** [comment]
This is likely one of a few issues:

* DNS Issue
  * Make sure your external DNS is properly pointed to your public IP (using something like DuckDNS)
* Firewall/Router issue
  * Make sure ports 80 and 443 are forwarded on your firewall/router to the IP you have this add-on running on.
* ISP blocking TCP 80 or 443
  * If this is the case, you'll need to use another add-on to do let's encrypt that can do the DNS challenge (like the DuckDNS add-on.)
