### ISSUE TITLE
Unsupported architecture

### ISSUE THREAD

**Issue by massive** [korylprince/hassio-caddy#6]
Installation of the add-on fails & I'm getting this error when trying to install to Raspberry Pi 3 B+

```
19-03-09 10:58:13 ERROR (SyncWorker_13) [hassio.docker.interface] Can't install korylprince/hassio-caddy-armv7:1.4 -> 404 Client Error: Not Found ("pull access denied for korylprince/hassio-caddy-armv7, repository does not exist or may require 'docker login'").
```

I'm not even sure if this is supposed to be installable, but as armhf architecture Docker images exist for the addon, I guess it could be made to work?

Thanks

**Comment by korylprince** [comment]
It looks like they just added support for armv7 a few days ago. I've updated the add-on to 1.5 and added a build for armv7. Please try to install the add-on now and let me know if you have any issues.
