### ISSUE TITLE
Feature Request: Service to enable/disable proxies

### ISSUE THREAD

**Issue by Devqon** [korylprince/hassio-caddy#8]
Is it possible to dynamically enable/disable proxies from the Caddy config?
My use case is that I want to add my router behind a reversed proxy. But for security reasons I don't want it always on, only when I specifically enable it.
I know I can do this by editing the Caddyfile and then restart the addon, but I was wondering if there could be made a service to trigger it from Home assistant.

**Comment by korylprince** [comment]
This is outside of the scope of this add-on.

You could always use the `hassio.addon_start` and `hassio.addon_stop` services to stop and start the Caddy add-on.

Additionally, Caddy 2, which is currently in development, will include a [configuration API](https://github.com/caddyserver/caddy/wiki/v2:-Documentation#admin-endpoint) that would likely do everything you're wanting and more.

In any case, this add-on is meant to be a simple wrapper over Caddy, and I don't want to build in a bunch of extra logic.

**Comment by Devqon** [comment]
Awesome, this answers my questions thank you
