### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by arissaraiva** [korylprince/hassio-caddy#9]
Hi,
I´m trying to run caddy on hassio 0.98.2 but I keep receiving this error:
```
Using built-in Caddy: Caddy 0.11.1 (unofficial)
Running Caddy:  /usr/sbin/caddy -conf /share/caddy/Caddyfile -agree -email arissaraiva@gmail.com
2019/09/05 19:47:12 loading Caddyfile via flag: open /share/caddy/Caddyfile: no such file or directory
```
my Caddyfile is placed in /share/caddy and it´s written like this:

```
mydomain.duckdns.org {
    header / {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
}
    proxy / localhost:8123 {
        websocket
        transparent
    }
}
```
and my addon config is like this:

```
{
  "flags": [
    "-agree",
    "-email",
    "myemail@gmail.com"
  ],
  "env_vars": []
}
```

anyone could help me

**Comment by korylprince** [comment]
While you say your Caddyfile is located at `/share/caddy/Caddyfile`, the log indicates otherwise. How did you transfer the file? Are you sure the filename case is correct (Caddyfile vs caddyfile)?

**Comment by arissaraiva** [comment]
Thanks for the reply,
yes I tried the both Caddyfile x caddyfile, and resulted in the same errors.

**Comment by korylprince** [comment]
How did you transfer the file?

**Comment by arissaraiva** [comment]
I hello,
Im using hassio in a rpi so I used samba to put the file into the folder. Use note+ tô create the file.

**Comment by korylprince** [comment]
You'll have to do some investigation. Create a text file with the contents (copy and paste):

``` bash
#!/bin/sh
find /share/caddy
```

Save it to a file called `caddy.bin`. Make sure your text editor doesn't add the `.txt` extension on the end.

Put it in the `/share/caddy` folder on your Hass.io instance.

Now restart the add-on and let me know what the logs show.

**Comment by arissaraiva** [comment]
sorry for the long time but was away from home:

here´s the log after adding cady.bin

```
> /run.sh: /share/caddy/caddy.bin: /bin/sh^M: bad interpreter: No such file or directory
> Found custom Caddy: 
> Running Caddy:  /share/caddy/caddy.bin -conf /share/caddy/Caddyfile -agree -email arissaraiva@gmail.com
> env: ‘/share/caddy/caddy.bin’: No such file or directory
```

**Comment by korylprince** [comment]
You need to use an editor like notepad++ to ensure the file has Unix line endings. You're getting that error because your file has DOS line endings.

**Comment by arissaraiva** [comment]
Hi Im using notepad++ something different I should use?

**Comment by korylprince** [comment]
See [this](https://stackoverflow.com/questions/8195839/choose-newline-character-in-notepad) about setting the line endings with Notepad++.

**Comment by arissaraiva** [comment]
Hi,
changed the sttings/preferences/new doc to UNIX, but in the end had the same logs.

rgds

**Comment by korylprince** [comment]
Okay, let's try this. Download [this file](https://gist.githubusercontent.com/korylprince/05c77145ce23feb234df9b940274691b/raw/a4c6d30383ec240b6457e7d38df9387d99bb68dc/caddy.bin), and put it place of the one you created.

**Comment by korylprince** [comment]
Closed for lack of updates.
